import mongoose from 'mongoose';

const base = { owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true } };
const schema = (fields) => new mongoose.Schema({ ...base, ...fields }, { timestamps: true });

export const User = mongoose.model('User', new mongoose.Schema({ name: { type: String, required: true }, email: { type: String, required: true, unique: true, lowercase: true }, password: { type: String, required: true } }, { timestamps: true }));
export const Project = mongoose.model('Project', schema({ name: { type: String, required: true }, clientName: String, clientPhone: String, location: String, type: { type: String, default: 'Residential' }, startDate: Date, dueDate: Date, status: { type: String, enum: ['Planning','Ongoing','On Hold','Completed'], default: 'Planning' }, budget: { type: Number, default: 0 }, notes: String, description: String, progress: { type: Number, default: 0 } }));
export const Client = mongoose.model('Client', schema({ name: { type: String, required: true }, phone: String, email: String, address: String, project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' }, contractAmount: { type: Number, default: 0 }, notes: String }));
export const Worker = mongoose.model('Worker', schema({ name: { type: String, required: true }, phone: String, role: { type: String, default: 'Helper' }, category: { type: String, enum: ['Worker','Contractor'], default: 'Worker' }, project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' }, joiningDate: Date, dailyRate: { type: Number, default: 0 }, paymentType: { type: String, default: 'Daily' }, status: { type: String, enum: ['Active','Inactive'], default: 'Active' } }));
export const Attendance = mongoose.model('Attendance', schema({ worker: { type: mongoose.Schema.Types.ObjectId, ref: 'Worker', required: true }, project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true }, date: { type: Date, required: true }, status: { type: String, enum: ['Present','Absent','Half Day','Leave','Holiday'], required: true } }).index({ owner: 1, worker: 1, date: 1 }, { unique: true }));
export const Payment = mongoose.model('Payment', schema({ worker: { type: mongoose.Schema.Types.ObjectId, ref: 'Worker' }, client: { type: mongoose.Schema.Types.ObjectId, ref: 'Client' }, project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' }, amount: { type: Number, required: true }, date: { type: Date, default: Date.now }, method: { type: String, default: 'Cash' }, transactionId: String, remarks: String }));
export const SiteUpdate = mongoose.model('SiteUpdate', schema({ project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true }, date: { type: Date, default: Date.now }, work: String, progress: { type: Number, min: 0, max: 100 }, materials: String, issues: String, observations: String, remarks: String, nextWork: String, photos: [String] }));
export const Timeline = mongoose.model('Timeline', schema({ project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true }, stage: { type: String, required: true }, status: { type: String, enum: ['Not Started','In Progress','Completed','Delayed','Upcoming'], default: 'Not Started' }, order: Number, completedAt: Date }));
